config/routes.rb
LogHorizonBlog::Application.routes.draw do
  
  root 'welcome#index'
  get '/about', to: 'welcome#about'
  get '/archives/:year_id/:month_id', to: 'archives#show'
  get '/archives/:year_id', to: 'archives#show'

  resources :articles, only: [:index, :show]
  resources :tags
  resources :archives
  resources :admin, only: :index

  namespace :admin do
    resources :articles
  end

  scope 'admin' do
    devise_for :users
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
  validates :content, presence: true
  has_and_belongs_to_many :tags

  after_save do |article|
    article.update_columns(count: 0)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 5 }
  has_and_belongs_to_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < BaseController
    # load_resource

    def new
      @article = Article.new
      @tag = Tag.all
    end

    def index
      @articles = Article.all
    end
    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to @article, flash: {notice: "Article post successfully."}
      else
        render 'new', flash: {alert: "something was wrong"}
      end
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      @article = Article.find(params[:id])
      if @article.update(article_params)
        redirect_to @article
      end
      render 'edit'
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      
      redirect_to admin_articles_path
    end
    private
    def article_params
      split_tags
      params.require(:article).permit(:title, :content, tag_ids: [])
    end
    def split_tags
      tag_ids = []
      tags = params[:tags].split(";")
      for tag in tags
        tagObject = Tag.find_by(name: tag)
        if tagObject
          tag_ids.push(tagObject.id)
        else
          newTag = Tag.create(name: tag)
          tag_ids.push(newTag.id)
        end
      end
      params[:article][:tag_ids] = tag_ids
    end
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    layout 'admin_layout'
    before_filter :verify_admin

    private
    def verify_admin
      redirect_to new_user_session_path unless current_user
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    redirect_to admin_articles_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admin_index_path
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @articles_month = Article.all.group_by{ |a| a.created_at.beginning_of_year }
  end
  def show
    if params[:month_id] && params[:year_id]
      @articles_month = Article.all.group_by{|a| a.created_at.beginning_of_month}
      @articles_month.each do |month, array|
        if month.year.to_s == params[:year_id] && month.month.to_s == params[:month_id]
          @result = array
        end
      end
    elsif params[:year_id]
      @articles_year = Article.all.group_by{|a| a.created_at.beginning_of_year}
      @articles_year.each do |year, array|
        if year.year.to_s == params[:year_id]
          @result = array
        end
      end
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    count = @article.count
    @article.update_columns(count: count+1)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    page_count = Article.all.count / 5
    if params[:page].to_i <= page_count
      @articles = Article.limit(5).offset(params[:page].to_i()*5)
    else
      @articles = Article.limit(5)
      params[:page] = 0
    end
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def markdown(text)
    # Redcarpet.new(text).to_html.html_safe
  # end
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
    no_intra_emphasis: true,
    fenced_code_blocks: true,
    disable_indented_code_blocks: true)
    return markdown.render(text).html_safe
  end

end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/articles/_form.html.slim
== form_for [:admin, @article] do |f|
  - if @article.errors.any?
    div#error_explanation
      h2
        == pluralize(@article.errors.count, "error")
        prohibited this article from being saved:
      ul
        - @article.errors.full_messages.each do |msg|
          li 
            == msg
  div.ui.input
    == f.label :title
    == f.text_field :title
  br
  div.ui.input
    == label_tag 'tags'
    == text_field_tag 'tags'
  br
  div.ui.reply.form
    == f.label :content
    == f.text_area :content
  br
  div.ui.input
    == f.submit

  hr
  - Tag.find_each do |tag|
    div.ui.tag.label == tag.name

app/views/admin/articles/edit.html.slim
div.ui.attached.segment
  == render 'form'

app/views/admin/articles/index.html.slim
h2 Manage Articles
== link_to 'New Articles poi~',new_admin_article_path
table.ui.table
  thead
    tr
      th Title
      th Tags
      th Counts
      th Created_at
      th Operation
  tbody
    - @articles.each do |article|
      tr
        td == article.title
        td
          - article.tags.each do |tag|
            a.ui.tag.label.tiny[href="#{tag_path(tag)}"] == tag.name
        td == article.count
        td == article.created_at
        td 
          == link_to 'Edit', edit_admin_article_path(article)
          == link_to 'Destroy', admin_article_path(article), method: :delete, data: {confirm: 'Are you sure?'} 

app/views/admin/articles/new.html.slim
div.ui.attached.segment
  h1 New Article

  == render 'form'

app/views/archives/index.html.slim
div.ui.attached.segment 
  - @articles_month.sort.reverse.each do |year, articless|
    ul
      li
        h2 == year.strftime("%G")
        - articless.group_by { |a| a.created_at.beginning_of_month }.each do |month, articles|
          ul
            li
              h4 == month.strftime("%B")
              ul
                - for article in articles
                  li 
                    == link_to article.title, article_path(article)

app/views/archives/show.html.slim
div.ui.attached.segment
  - if params[:month_id] && params[:year_id] && @result
    - @result.each do |item|
      ul
        li
          h2 #{params[:year_id]}/#{params[:month_id]}
          ul
            li
              == link_to item.title, article_path(item)
  - elsif params[:year_id] && @result 
    - @result.group_by{|a| a.created_at.beginning_of_month}.each do |year, items|
      ul
        li
          h2  #{params[:year_id]}/#{year.month}
          ul
            - items.each do |item| 
              li
                == link_to item.title, article_path(item)

          

app/views/articles/_form.html.slim
== form_for @article do |f|
  - if @article.errors.any?
    div#error_explanation
      h2
        == pluralize(@article.errors.count, "error")
        prohibited this article from being saved:
      ul
        - @article.errors.full_messages.each do |msg|
          li 
            == msg
  p
    == f.label :title
    == f.text_field :title
  p
    == label_tag 'tags'
    == text_field_tag 'tags'
  p
    == f.label :content
    == f.text_area :content
  p
    == f.submit

  hr
  - Tag.find_each do |tag|
    div.ui.tag.label == tag.name

app/views/articles/index.html.slim
div.ui.attached.segment
  - @articles.each do |article|
    h2.ui.header
      == link_to article.title, article_path(article)
    div.sub.header
      == article.created_at.strftime("%Y %m %d, %A")
    p
      - article.tags.each do |tag|
        a.ui.tag.label.tiny[href="#{tag_path(tag)}"] == tag.name
    div.content
      == article.content

app/views/articles/show.html.slim
div.ui.attached.segment
  h2
    strong == @article.title
  - @article.tags.each do |tag|
    a.ui.tag.label.tiny[href="#{tag_path(tag)}"] == tag.name
  hr
  p == markdown @article.content
  div[class="ds-thread" data-thread-key="#{@article.id}" data-title="#{@article.title}" data-url="#{request.original_url}"]

app/views/layouts/admin_layout.html.slim
doctype html
html
  head
    title == ENV['title']
    == stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    == javascript_include_tag "application", "data-turbolinks-track" => true
    == csrf_meta_tags
  body
    div.ui.grid
      div.one.column.row
        div.column
          div.row[style="margin: 0 auto;width: 1024px"]
            h1 Admin
            - if current_user
              p == link_to 'Log out', destroy_user_session_path, method: :delete
            hr
            == yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title wall2flower的生存报告
    == stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    == javascript_include_tag "application", "data-turbolinks-track" => true
    == csrf_meta_tags

  body
    p.notice = notice
    p.alert = alert
    div.ui.grid[style="width: 1024px;margin: 0 auto;"]
      div.one.column.row
        div.column
          h1 == ENV['title']
          p == ENV['subtitle']
          div.ui.tabular.menu
            a[href="#{root_path}" class="item #{'active' if params[:controller] == 'welcome' and params[:action] == 'index'}"] Index
            a[href="#{archives_path}" class="item #{'active' if params[:controller] == 'archives'}"] Archives
            a[href="#{about_path}" class="item #{'active' if params[:action] == 'about' && params[:controller] == 'welcome'}"] About
      
      div.row
        div.twelve.wide.column.typo
          == yield
        div.four.wide.column
          div.ui.card
            div.image.dimmable
              == image_tag ENV['avater_url']
            div.content
              div.description == ENV['personal_desc']

          div.ui.top.attached.header Tags
          div.ui.attached.segment
            p
              - Tag.find_each do |tag|
                a.ui.tag.label.small[href="#{tag_path(tag)}" style="margin-bottom: 4px;margin-right: 4px;"] #{tag.name}(#{tag.articles.count})
          div.ui.top.attached.header Archives
          div.ui.attached.segment
            - Article.all.group_by { |a| a.created_at.beginning_of_year }.sort.reverse.each do |year, a_year|
              - a_year.group_by{ |a| a.created_at.beginning_of_month }.each do |month, a_month|
                p
                  a[href="/archives/#{month.year}/#{month.month}"] #{month.strftime("%G %B")}(#{a_month.count})

  javascript:
    var duoshuoQuery = {short_name:"loghorizon"};
      (function() {
        var ds = document.createElement('script');
        ds.type = 'text/javascript';ds.async = true;
        ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
        ds.charset = 'UTF-8';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ds);
      })();

app/views/tags/show.html.slim
div.ui.attached.segment
  h4.ui.label == @tag.name
  ul
    - @tag.articles.each do |article|
      li
        == link_to article.title, article_path(article)

app/views/welcome/about.html.slim
div.ui.attached.segment
  h2 About

app/views/welcome/index.html.slim
div.ui.attached.segment  
  - @articles.sort.reverse.each do |article|
    h2.ui.header
      == link_to article.title, article_path(article)
    div.sub.header
      == article.created_at.strftime("%Y %m月%d日, %A")
    p 
      - article.tags.each do |tag|
        a.ui.tag.label.tiny[href="#{tag_path(tag)}"] == tag.name
    div.content
      == article.content
div.ui.bottom.attached.header
  div[class="ui buttons"]
    - article_count = Article.all.count
    - if article_count%5 != 0
      - page_array = (0..(article_count/5)).to_a
    - else
      - page_array = (0..((article_count/5)-1)).to_a

    - page_array.each do |i|
      - if params[:page].to_i === i
        a.ui.button.active[href="#{root_path(page: i)}"] == i
      - else
        a.ui.button[href="#{root_path(page: i)}"] == i

    /* - (0..(Article.all.count/5)-1).each do |i| */
    /*   - if params[:page].to_i === i */
    /*     a.ui.button.active[href="#{root_path(page: i)}"] == i */
    /*   - else */
    /*     a.ui.button[href="#{root_path(page: i)}"] == i */